[package]
name = "derive-macro"
version = "0.1.0"
edition = "2018"

[lib]
crate_type = ["proc-macro"]
#proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full","fold"] }
quote = "1.0"
proc-macro2 = "1.0"